library(ggplot2)
library(tidyverse)
library(RColorBrewer)
fulldata <- read.csv("https://raw.githubusercontent.com/BrunaLab/HeliconiaREU-Ellie/4dd4b10a923aaa526b6e3f1c5253d5513293b4d1/num_plants_experiment.csv") #Reading in data generated by previous code
fulldata2 <- separate(fulldata, experiment, c("x","n_plants")) %>% mutate(n_plants = as.factor(as.numeric(n_plants))) # Mutating the n_plants variable to allow for plotting
fulldata2


# Creation of boxplots for each parameter extracted from the GAMs performed earlier
# Plots center and spread of each parameter
r2boxplot <- ggplot(fulldata2 , aes(x = n_plants, y= r2))+ geom_boxplot(aes(fill=n_plants), 
  outlier.color = "red") + scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 1", x = "Number of Plants Per Sample", y = "R Squared") + 
  theme_classic() + theme(legend.position = "none") 
rmseboxplot <- ggplot(fulldata2 , aes(x = n_plants, y= rmse))+ geom_boxplot(aes(fill=n_plants), 
  outlier.color = "red")+scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 2", x = "Number of Plants Per Sample", y = "Root Mean Squared Error") + 
  theme_classic() + theme(legend.position = "none")
edfboxplot <- ggplot(fulldata2 , aes(x = n_plants, y= edf))+ geom_boxplot(aes(fill=n_plants), 
  outlier.color = "red")+scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 3", x = "Number of Plants Per Sample", y = "Estimated Degrees of Freedom (GAM)") + 
  theme_classic() + theme(legend.position = "none")
pvalueboxplot <- ggplot(fulldata2 , aes(x = n_plants, y= pvalue))+ geom_boxplot(aes(fill=n_plants), 
  outlier.color = "red")+scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 4", x = "Number of Plants Per Sample", y = "P Value (GAM)") + 
  theme_classic() + theme(legend.position = "none")

r2boxplot
rmseboxplot
edfboxplot
pvalueboxplot

# Function created to run the stat_summary command within violin plots. Adds a point at the mean and a line showing +/- one standard deviation
data_summary <- function(x) {
  m <- mean(x)
  ymin <- m-sd(x)
  ymax <- m+sd(x)
  return(c(y=m,ymin=ymin,ymax=ymax))
}

# Creation of violin plots for each parameter. Plots spread and density
# P Value was eliminated as the majority of values were 0 or nearly 0, rendering a violin plot useless
r2violinplot <- ggplot(fulldata2 , aes(x = n_plants, y= r2))+ geom_violin(aes(fill=n_plants)) + 
  scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 5", x = "Number of Plants Per Sample", y = "R Squared") + 
  theme_classic() + theme(legend.position = "none") + stat_summary(fun.data=data_summary)
rmseviolinplot <- ggplot(fulldata2 , aes(x = n_plants, y= log(rmse)))+ geom_violin(aes(fill=n_plants)) + 
  scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 6", x = "Number of Plants Per Sample", y = "Root Mean Squared Error") + 
  theme_classic() + theme(legend.position = "none") + stat_summary(fun.data=data_summary)
edfviolinplot <- ggplot(fulldata2 , aes(x = n_plants, y= log(edf)))+ geom_violin(aes(fill=n_plants)) + 
  scale_fill_brewer(palette="OrRd") + 
  labs(title = "Figure 7", x = "Number of Plants Per Sample", y = "Estimated Degrees of Freedom (GAM)") + 
  theme_classic() + theme(legend.position = "none") + stat_summary(fun.data=data_summary)

r2violinplot
rmseviolinplot
edfviolinplot



